//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummitService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public int ID_Variant { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public int Country_ID { get; set; }
        public int User_ID { get; set; }
        public int Summit_ID { get; set; }
    }
}
