//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SummitService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voice
    {
        public int ID_Voice { get; set; }
        public int User_ID { get; set; }
        public int Variant_ID { get; set; }
    }
}
